name = "JuliaForDataScience"
uuid = "ef08b6a7-da18-4058-82ae-89e8e5fcf195"
authors = ["joshday <emailjoshday@gmail.com>"]
version = "0.1.0"

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
